version: '3'
services:
  node1:
    build: DHT
    entrypoint: ["dotnet", "DHT.dll","${PUBLIC_IP}","9000","node1"]
  node2:
    build: DHT
    entrypoint: ["dotnet", "DHT.dll","${PUBLIC_IP}","9001","node2"]
  node3:
    build: DHT
    entrypoint: ["dotnet", "DHT.dll","${PUBLIC_IP}","9002","node3"]